insert into user_account(userid, username, password, active) values (1, 'user1', 'user1', 1);
insert into user_account(userid, username, password, active) values (2, 'user2', 'user2', 1);
insert into user_account(userid, username, password, active) values (3, 'admin', 'admin', 1);
insert into user_role(id, role_name) values (1, 'USER');
insert into user_role(id, role_name) values (2, 'ADMIN');
insert into user_role(id, role_name) values (3, 'USER');
insert into user_to_role(id, userid, role_id) values (1, 1, 1);
insert into user_to_role(id, userid, role_id) values (2, 2, 1);
insert into user_to_role(id, userid, role_id) values (3, 3, 2);
insert into user_privilege(id, privilege_name) values (1, 'readUser');
insert into user_privilege(id, privilege_name) values (2, 'readAdmin');
insert into user_privilege(id, privilege_name) values (3, 'readAdmin');
insert into user_role_to_privilege(id, role_id, privilege_id) values (1, 1, 1);
insert into user_role_to_privilege(id, role_id, privilege_id) values (2, 2, 1);
insert into user_role_to_privilege(id, role_id, privilege_id) values (3, 2, 2);